// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ai_service {

static const char* TensorRTEngine_method_names[] = {
  "/ai_service.TensorRTEngine/RunInference",
};

std::unique_ptr< TensorRTEngine::Stub> TensorRTEngine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TensorRTEngine::Stub> stub(new TensorRTEngine::Stub(channel, options));
  return stub;
}

TensorRTEngine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RunInference_(TensorRTEngine_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TensorRTEngine::Stub::RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::ai_service::InferResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ai_service::InferRequest, ::ai_service::InferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RunInference_, context, request, response);
}

void TensorRTEngine::Stub::async::RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ai_service::InferRequest, ::ai_service::InferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunInference_, context, request, response, std::move(f));
}

void TensorRTEngine::Stub::async::RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunInference_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>* TensorRTEngine::Stub::PrepareAsyncRunInferenceRaw(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ai_service::InferResponse, ::ai_service::InferRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RunInference_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>* TensorRTEngine::Stub::AsyncRunInferenceRaw(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRunInferenceRaw(context, request, cq);
  result->StartCall();
  return result;
}

TensorRTEngine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TensorRTEngine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TensorRTEngine::Service, ::ai_service::InferRequest, ::ai_service::InferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TensorRTEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ai_service::InferRequest* req,
             ::ai_service::InferResponse* resp) {
               return service->RunInference(ctx, req, resp);
             }, this)));
}

TensorRTEngine::Service::~Service() {
}

::grpc::Status TensorRTEngine::Service::RunInference(::grpc::ServerContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ai_service

