// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_inference_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_inference_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_inference_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_inference_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_inference_2eproto;
namespace ai_service {
class InferRequest;
struct InferRequestDefaultTypeInternal;
extern InferRequestDefaultTypeInternal _InferRequest_default_instance_;
class InferResponse;
struct InferResponseDefaultTypeInternal;
extern InferResponseDefaultTypeInternal _InferResponse_default_instance_;
}  // namespace ai_service
PROTOBUF_NAMESPACE_OPEN
template<> ::ai_service::InferRequest* Arena::CreateMaybeMessage<::ai_service::InferRequest>(Arena*);
template<> ::ai_service::InferResponse* Arena::CreateMaybeMessage<::ai_service::InferResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ai_service {

// ===================================================================

class InferRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ai_service.InferRequest) */ {
 public:
  inline InferRequest() : InferRequest(nullptr) {}
  ~InferRequest() override;
  explicit PROTOBUF_CONSTEXPR InferRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InferRequest(const InferRequest& from);
  InferRequest(InferRequest&& from) noexcept
    : InferRequest() {
    *this = ::std::move(from);
  }

  inline InferRequest& operator=(const InferRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferRequest& operator=(InferRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InferRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const InferRequest* internal_default_instance() {
    return reinterpret_cast<const InferRequest*>(
               &_InferRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InferRequest& a, InferRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(InferRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InferRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InferRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InferRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InferRequest& from) {
    InferRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InferRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ai_service.InferRequest";
  }
  protected:
  explicit InferRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageDataFieldNumber = 1,
    kWidthFieldNumber = 2,
    kHeightFieldNumber = 3,
  };
  // bytes image_data = 1;
  void clear_image_data();
  const std::string& image_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_data();
  PROTOBUF_NODISCARD std::string* release_image_data();
  void set_allocated_image_data(std::string* image_data);
  private:
  const std::string& _internal_image_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_data(const std::string& value);
  std::string* _internal_mutable_image_data();
  public:

  // int32 width = 2;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 3;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ai_service.InferRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_data_;
    int32_t width_;
    int32_t height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// -------------------------------------------------------------------

class InferResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ai_service.InferResponse) */ {
 public:
  inline InferResponse() : InferResponse(nullptr) {}
  ~InferResponse() override;
  explicit PROTOBUF_CONSTEXPR InferResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InferResponse(const InferResponse& from);
  InferResponse(InferResponse&& from) noexcept
    : InferResponse() {
    *this = ::std::move(from);
  }

  inline InferResponse& operator=(const InferResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferResponse& operator=(InferResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InferResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const InferResponse* internal_default_instance() {
    return reinterpret_cast<const InferResponse*>(
               &_InferResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InferResponse& a, InferResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(InferResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InferResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InferResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InferResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InferResponse& from) {
    InferResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InferResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ai_service.InferResponse";
  }
  protected:
  explicit InferResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBoundingBoxesFieldNumber = 2,
    kMessageFieldNumber = 3,
    kSuccessFieldNumber = 1,
  };
  // repeated float bounding_boxes = 2;
  int bounding_boxes_size() const;
  private:
  int _internal_bounding_boxes_size() const;
  public:
  void clear_bounding_boxes();
  private:
  float _internal_bounding_boxes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_bounding_boxes() const;
  void _internal_add_bounding_boxes(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_bounding_boxes();
  public:
  float bounding_boxes(int index) const;
  void set_bounding_boxes(int index, float value);
  void add_bounding_boxes(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      bounding_boxes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_bounding_boxes();

  // string message = 3;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ai_service.InferResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > bounding_boxes_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InferRequest

// bytes image_data = 1;
inline void InferRequest::clear_image_data() {
  _impl_.image_data_.ClearToEmpty();
}
inline const std::string& InferRequest::image_data() const {
  // @@protoc_insertion_point(field_get:ai_service.InferRequest.image_data)
  return _internal_image_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InferRequest::set_image_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ai_service.InferRequest.image_data)
}
inline std::string* InferRequest::mutable_image_data() {
  std::string* _s = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:ai_service.InferRequest.image_data)
  return _s;
}
inline const std::string& InferRequest::_internal_image_data() const {
  return _impl_.image_data_.Get();
}
inline void InferRequest::_internal_set_image_data(const std::string& value) {
  
  _impl_.image_data_.Set(value, GetArenaForAllocation());
}
inline std::string* InferRequest::_internal_mutable_image_data() {
  
  return _impl_.image_data_.Mutable(GetArenaForAllocation());
}
inline std::string* InferRequest::release_image_data() {
  // @@protoc_insertion_point(field_release:ai_service.InferRequest.image_data)
  return _impl_.image_data_.Release();
}
inline void InferRequest::set_allocated_image_data(std::string* image_data) {
  if (image_data != nullptr) {
    
  } else {
    
  }
  _impl_.image_data_.SetAllocated(image_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_data_.IsDefault()) {
    _impl_.image_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ai_service.InferRequest.image_data)
}

// int32 width = 2;
inline void InferRequest::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t InferRequest::_internal_width() const {
  return _impl_.width_;
}
inline int32_t InferRequest::width() const {
  // @@protoc_insertion_point(field_get:ai_service.InferRequest.width)
  return _internal_width();
}
inline void InferRequest::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void InferRequest::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:ai_service.InferRequest.width)
}

// int32 height = 3;
inline void InferRequest::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t InferRequest::_internal_height() const {
  return _impl_.height_;
}
inline int32_t InferRequest::height() const {
  // @@protoc_insertion_point(field_get:ai_service.InferRequest.height)
  return _internal_height();
}
inline void InferRequest::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void InferRequest::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:ai_service.InferRequest.height)
}

// -------------------------------------------------------------------

// InferResponse

// bool success = 1;
inline void InferResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool InferResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool InferResponse::success() const {
  // @@protoc_insertion_point(field_get:ai_service.InferResponse.success)
  return _internal_success();
}
inline void InferResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void InferResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:ai_service.InferResponse.success)
}

// repeated float bounding_boxes = 2;
inline int InferResponse::_internal_bounding_boxes_size() const {
  return _impl_.bounding_boxes_.size();
}
inline int InferResponse::bounding_boxes_size() const {
  return _internal_bounding_boxes_size();
}
inline void InferResponse::clear_bounding_boxes() {
  _impl_.bounding_boxes_.Clear();
}
inline float InferResponse::_internal_bounding_boxes(int index) const {
  return _impl_.bounding_boxes_.Get(index);
}
inline float InferResponse::bounding_boxes(int index) const {
  // @@protoc_insertion_point(field_get:ai_service.InferResponse.bounding_boxes)
  return _internal_bounding_boxes(index);
}
inline void InferResponse::set_bounding_boxes(int index, float value) {
  _impl_.bounding_boxes_.Set(index, value);
  // @@protoc_insertion_point(field_set:ai_service.InferResponse.bounding_boxes)
}
inline void InferResponse::_internal_add_bounding_boxes(float value) {
  _impl_.bounding_boxes_.Add(value);
}
inline void InferResponse::add_bounding_boxes(float value) {
  _internal_add_bounding_boxes(value);
  // @@protoc_insertion_point(field_add:ai_service.InferResponse.bounding_boxes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
InferResponse::_internal_bounding_boxes() const {
  return _impl_.bounding_boxes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
InferResponse::bounding_boxes() const {
  // @@protoc_insertion_point(field_list:ai_service.InferResponse.bounding_boxes)
  return _internal_bounding_boxes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
InferResponse::_internal_mutable_bounding_boxes() {
  return &_impl_.bounding_boxes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
InferResponse::mutable_bounding_boxes() {
  // @@protoc_insertion_point(field_mutable_list:ai_service.InferResponse.bounding_boxes)
  return _internal_mutable_bounding_boxes();
}

// string message = 3;
inline void InferResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& InferResponse::message() const {
  // @@protoc_insertion_point(field_get:ai_service.InferResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InferResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ai_service.InferResponse.message)
}
inline std::string* InferResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:ai_service.InferResponse.message)
  return _s;
}
inline const std::string& InferResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void InferResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* InferResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* InferResponse::release_message() {
  // @@protoc_insertion_point(field_release:ai_service.InferResponse.message)
  return _impl_.message_.Release();
}
inline void InferResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ai_service.InferResponse.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ai_service

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_inference_2eproto
