// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto
// Original file comments:
// inference.proto
// gRPC 接口定义文件
// 用于 Python ↔ C++ 通信
//
#ifndef GRPC_inference_2eproto__INCLUDED
#define GRPC_inference_2eproto__INCLUDED

#include "inference.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ai_service {

// 定义服务 - 相当于 HTTP 的接口
class TensorRTEngine final {
 public:
  static constexpr char const* service_full_name() {
    return "ai_service.TensorRTEngine";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 一个 RPC 方法: 接收 InferRequest，返回 InferResponse
    virtual ::grpc::Status RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::ai_service::InferResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai_service::InferResponse>> AsyncRunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai_service::InferResponse>>(AsyncRunInferenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai_service::InferResponse>> PrepareAsyncRunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai_service::InferResponse>>(PrepareAsyncRunInferenceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 一个 RPC 方法: 接收 InferRequest，返回 InferResponse
      virtual void RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ai_service::InferResponse>* AsyncRunInferenceRaw(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ai_service::InferResponse>* PrepareAsyncRunInferenceRaw(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::ai_service::InferResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>> AsyncRunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>>(AsyncRunInferenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>> PrepareAsyncRunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>>(PrepareAsyncRunInferenceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response, std::function<void(::grpc::Status)>) override;
      void RunInference(::grpc::ClientContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>* AsyncRunInferenceRaw(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ai_service::InferResponse>* PrepareAsyncRunInferenceRaw(::grpc::ClientContext* context, const ::ai_service::InferRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RunInference_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 一个 RPC 方法: 接收 InferRequest，返回 InferResponse
    virtual ::grpc::Status RunInference(::grpc::ServerContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RunInference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunInference() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RunInference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunInference(::grpc::ServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunInference(::grpc::ServerContext* context, ::ai_service::InferRequest* request, ::grpc::ServerAsyncResponseWriter< ::ai_service::InferResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RunInference<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RunInference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RunInference() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ai_service::InferRequest, ::ai_service::InferResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ai_service::InferRequest* request, ::ai_service::InferResponse* response) { return this->RunInference(context, request, response); }));}
    void SetMessageAllocatorFor_RunInference(
        ::grpc::MessageAllocator< ::ai_service::InferRequest, ::ai_service::InferResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ai_service::InferRequest, ::ai_service::InferResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RunInference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunInference(::grpc::ServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunInference(
      ::grpc::CallbackServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RunInference<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RunInference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunInference() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RunInference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunInference(::grpc::ServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunInference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunInference() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RunInference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunInference(::grpc::ServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunInference(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RunInference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RunInference() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RunInference(context, request, response); }));
    }
    ~WithRawCallbackMethod_RunInference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunInference(::grpc::ServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunInference(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RunInference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RunInference() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ai_service::InferRequest, ::ai_service::InferResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ai_service::InferRequest, ::ai_service::InferResponse>* streamer) {
                       return this->StreamedRunInference(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RunInference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunInference(::grpc::ServerContext* /*context*/, const ::ai_service::InferRequest* /*request*/, ::ai_service::InferResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRunInference(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ai_service::InferRequest,::ai_service::InferResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RunInference<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RunInference<Service > StreamedService;
};

}  // namespace ai_service


#endif  // GRPC_inference_2eproto__INCLUDED
